"""Orchestrator — coordinates all agents into a multi-step pipeline."""

from __future__ import annotations

import structlog

from agents.polymarket_agent import PolymarketAgent
from agents.kalshi_agent import KalshiAgent
from agents.niche_agent import NicheAgent
from agents.rag_enrichment_agent import RAGEnrichmentAgent
from agents.learning_loop_agent import LearningLoopAgent
from models.trader import TraderProfile
from scoring.scorer import TraderScorer
from tools.data_store import DataStore

logger = structlog.get_logger(__name__)


class Orchestrator:
    """Coordinates agents and scoring into a full discovery pipeline.

    Pipeline:
        1. Fetch traders from Polymarket (real leaderboard)
        2. Fetch markets from Kalshi (as pseudo-traders)
        3. Classify traders into niches (LLM + keyword fallback)
        4. Enrich top events with web-scraped context (Apify + RAG)
        5. Score & rank all traders
        6. Persist to SQLite database
        7. Run closed learning loop (skill extraction + memory)
        8. Return ranked traders
    """

    def __init__(self):
        self.polymarket_agent = PolymarketAgent()
        self.kalshi_agent = KalshiAgent()
        self.niche_agent = NicheAgent()
        self.rag_agent = RAGEnrichmentAgent()
        self.learning_loop = LearningLoopAgent()
        self.scorer = TraderScorer()
        self.data_store = DataStore()
        self.logger = logger.bind(component="orchestrator")

    async def discover_traders(
        self,
        category: str = "OVERALL",
        limit: int = 10,
    ) -> list[TraderProfile]:
        """Full discovery pipeline: Fetch → Classify → Enrich → Score → Learn.

        Args:
            category: Leaderboard category (OVERALL, POLITICS, SPORTS, etc.)
            limit: Max traders to fetch per platform.

        Returns:
            Scored and ranked list of TraderProfile objects (best first).
        """
        self.logger.info("pipeline_start", pipeline="discover_traders", category=category)

        # ── Step 1: Fetch traders from Polymarket ──────
        polymarket_traders = []
        try:
            polymarket_traders = await self.polymarket_agent.fetch_traders(
                category=category,
                limit=limit,
            )
            self.logger.info("step_done", step="polymarket_fetch", count=len(polymarket_traders))
        except Exception as e:
            self.logger.error("polymarket_failed", error=str(e))

        # ── Step 2: Fetch markets from Kalshi ──────────
        kalshi_traders = []
        try:
            kalshi_traders = await self.kalshi_agent.fetch_traders(limit=limit)
            self.logger.info("step_done", step="kalshi_fetch", count=len(kalshi_traders))
        except Exception as e:
            self.logger.error("kalshi_failed", error=str(e))

        traders = polymarket_traders + kalshi_traders

        if not traders:
            self.logger.warning("pipeline_empty", reason="no traders from any source")
            return []

        # ── Step 3: Classify niches ────────────────────
        traders = self.niche_agent.map_niches_batch(traders)
        self.logger.info("step_done", step="niche_mapping", count=len(traders))

        # ── Step 4: Enrich top events via RAG ──────────
        try:
            # Enrich top Kalshi event titles (they have descriptive names)
            enrichment_targets = [
                t.display_name for t in kalshi_traders[:3]
                if t.display_name
            ]
            if enrichment_targets:
                self.rag_agent.enrich_batch(enrichment_targets, max_events=2)
                self.logger.info("step_done", step="rag_enrichment", events=len(enrichment_targets))
        except Exception as e:
            self.logger.warning("rag_enrichment_skipped", error=str(e))

        # ── Step 5: Score & Rank ───────────────────────
        ranked = self.scorer.rank(traders)
        self.logger.info("step_done", step="scoring", total=len(ranked))

        # ── Step 6: Persist to database ────────────────
        try:
            self.data_store.save_traders(ranked)
            self.logger.info("step_done", step="persistence")
        except Exception as e:
            self.logger.warning("persistence_failed", error=str(e))

        # ── Step 7: Closed learning loop ───────────────
        # (Run asynchronously, don't block the main pipeline)
        try:
            self.learning_loop.process_run_outcome(
                traders=ranked,
                recommendation="(pending — generated by chat agent)",
            )
            self.logger.info("step_done", step="learning_loop")
        except Exception as e:
            self.logger.warning("learning_loop_failed", error=str(e))

        self.logger.info(
            "pipeline_done",
            pipeline="discover_traders",
            total=len(ranked),
            top_score=ranked[0].composite_score if ranked else 0,
            polymarket_count=len(polymarket_traders),
            kalshi_count=len(kalshi_traders),
        )

        return ranked

    async def close(self):
        """Clean up resources."""
        try:
            await self.polymarket_agent.close()
        except Exception:
            pass
        try:
            await self.kalshi_agent.close()
        except Exception:
            pass
